### ISSUE TITLE
Please add a readme with a screen shot

### ISSUE THREAD

**Issue by unixorn** [m-lima/simpalt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by mlimat** [comment]
Hi @unixorn,
I made some changes to add compatibility with more plugin managers and frameworks. I also added a picture and `asciinema` demo.
Let me know if you think it is ok

**Comment by unixorn** [comment]
Nice! Added as https://github.com/unixorn/awesome-zsh-plugins/pull/609
